"""
Tokenizer Module

This module takes the textual narratives generated by the data pipeline and tokenizes them
into input arrays compatible with transformer models. It breaks matches down into overlapping 
sliding windows to create individual training samples, and automatically assigns logical 
momentum labels to each window based on xG (expected goals), field position, and outcomes.
"""
import os
import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer


# ── Helpers ───────────────────────────────────────────────────────────────────

def _line_token_positions(lines, tok):
    """
    Finds the exact start and end token indices for each line of match events in the narrative.
    Processing all lines at once in a batch significantly speeds up the conversion.
    """
    # Batch all lines at once: much faster than looping
    encoded = tok(
        [line + "\n" for line in lines],
        add_special_tokens=False,
        return_length=True,
    )
    lengths = np.array(encoded['length'], dtype=int)
    starts  = np.concatenate([[0], np.cumsum(lengths[:-1])])
    ends    = starts + lengths
    return starts.astype(int), ends.astype(int)


# ── Label computation ─────────────────────────────────────────────────────────

def _compute_labels(lines, meta_df, tok, context_length, stride,
                    label_window_minutes=5):
    """
    Assigns a 3-class momentum label to each sliding window.

    Classes:
      0 = Away Momentum  (Away team is clearly pressuring)
      1 = Balanced       (Game is neutral or ambiguous)
      2 = Home Momentum  (Home team is clearly pressuring)

    The logic hierarchy for determining momentum:
      1. Next Goal check: If a goal occurs within 20 mins, momentum favors the scoring team.
      2. Local xG calculation: Large disparity in expected goals favors the offensive team.
      3. Attacking Pressure: Number of actions in the opposing third determines pressure.
      4. Balanced: If none of the above are distinct, the state is considered balanced.
    """
    XG_THRESHOLD    = 0.15   # min xG diff to call it "momentum"
    PRESSURE_THRESH = 3      # min attacking-zone action diff
    GOAL_LOOKAHEAD  = 20 * 60

    line_starts, line_ends = _line_token_positions(lines, tok)
    total_tokens = int(line_ends[-1])

    is_home   = meta_df['is_home'].to_numpy(dtype=bool)
    xg_vals   = meta_df['xg'].to_numpy(dtype=float)
    time_secs = (meta_df['minute'].to_numpy(dtype=float) * 60
                 + meta_df['second'].to_numpy(dtype=float))
    is_goal   = meta_df['is_goal'].to_numpy(dtype=bool)

    in_attack_zone = np.array([
        'attacking third' in line or 'penalty area' in line
        for line in lines
    ], dtype=bool)

    labels        = []
    from_goal     = 0
    from_xg       = 0
    from_pressure = 0
    from_balanced = 0

    for w_start in range(0, total_tokens - context_length, stride):
        w_end   = w_start + context_length
        overlap = (line_starts < w_end) & (line_ends > w_start)

        w_time_end = time_secs[overlap].max() if overlap.any() else time_secs[-1]

        # ── 1. Next-goal within 20 min (decisive signal) ──────────────────
        future_goal_mask = (is_goal
                            & (time_secs > w_time_end)
                            & (time_secs <= w_time_end + GOAL_LOOKAHEAD))
        if future_goal_mask.any():
            first_idx = int(np.argmax(future_goal_mask))
            labels.append(2 if is_home[first_idx] else 0)
            from_goal += 1
            continue

        # ── 2. Window-local xG delta ──────────────────────────────────────
        if overlap.any():
            h_xg = float(xg_vals[overlap &  is_home].sum())
            a_xg = float(xg_vals[overlap & ~is_home].sum())
        else:
            h_xg = a_xg = 0.0

        diff = h_xg - a_xg
        if diff > XG_THRESHOLD:
            labels.append(2); from_xg += 1; continue
        elif diff < -XG_THRESHOLD:
            labels.append(0); from_xg += 1; continue

        # ── 3. Attacking-zone pressure ────────────────────────────────────
        if overlap.any():
            att     = overlap & in_attack_zone
            h_press = int((att &  is_home).sum())
            a_press = int((att & ~is_home).sum())
        else:
            h_press = a_press = 0

        pdiff = h_press - a_press
        if pdiff >= PRESSURE_THRESH:
            labels.append(2); from_pressure += 1
        elif pdiff <= -PRESSURE_THRESH:
            labels.append(0); from_pressure += 1
        else:
            labels.append(1); from_balanced += 1   # genuinely balanced

    total = len(labels)
    if total > 0:
        h_pct = 100 * sum(l == 2 for l in labels) / total
        b_pct = 100 * sum(l == 1 for l in labels) / total
        a_pct = 100 * sum(l == 0 for l in labels) / total
        print(f"  Label sources : goal={from_goal} xG={from_xg} "
              f"pressure={from_pressure} balanced={from_balanced}")
        print(f"  Classes       : Home={h_pct:.1f}%  "
              f"Balanced={b_pct:.1f}%  Away={a_pct:.1f}%")

    return torch.tensor(labels, dtype=torch.long)


# ── Public API ────────────────────────────────────────────────────────────────

def tokenize_match_narrative(input_file, match_id, meta_file,
                             output_dir="../data/pt-files",
                             model_name="gpt2",
                             context_length=256, stride=128,
                             label_window_minutes=5,
                             tok=None):
    """
    Tokenises a match narrative into overlapping sliding windows and generates
    a momentum label for each window using a tier-based momentum logic based on xG and goals.

    Args:
        tok: HuggingFace AutoTokenizer instance. Passed manually to avoid redundant reloading.

    Saves {'input_ids': Tensor[N, context_length], 'labels': Tensor[N]}
    to  match_{match_id}_dataset.pt in output_dir.
    """
    if tok is None:
        tok = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    with open(input_file, 'r', encoding='utf-8') as f:
        text = f.read()

    # ── Sliding-window input_ids ──────────────────────────────────────────
    all_ids = tok(text, return_tensors="pt", add_special_tokens=False)['input_ids'][0]
    print(f"  Total tokens : {len(all_ids)}")

    windows = []
    for i in range(0, len(all_ids) - context_length, stride):
        windows.append(all_ids[i : i + context_length])

    if not windows:
        print(f"  WARNING: match {match_id} too short for context_length={context_length}. Skipping.")
        return None

    input_ids = torch.stack(windows)           # [N, context_length]

    # ── Labels ───────────────────────────────────────────────────────────
    lines   = text.splitlines()
    meta_df = pd.read_csv(meta_file)

    required_cols = {'is_goal', 'cumulative_home_xg', 'cumulative_away_xg'}
    if not required_cols.issubset(meta_df.columns):
        raise ValueError(
            f"Meta CSV is missing columns {required_cols - set(meta_df.columns)}. "
            "Re-run data_pipeline.py to regenerate the meta file."
        )

    labels = _compute_labels(lines, meta_df, tok, context_length, stride,
                             label_window_minutes=label_window_minutes)

    assert len(input_ids) == len(labels), (
        f"Window/label count mismatch: {len(input_ids)} vs {len(labels)}"
    )

    counts = torch.bincount(labels, minlength=3)
    print(f"  Windows      : {len(input_ids)} x {context_length} tokens")
    print(f"  Final Distribution: Away={counts[0]} Balanced={counts[1]} Home={counts[2]}")

    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"match_{match_id}_dataset.pt")
    torch.save({'input_ids': input_ids, 'labels': labels}, output_file)
    print(f"  Saved → {output_file}")
    return output_file


if __name__ == "__main__":
    MATCH_ID   = 3754058
    INPUT_FILE = f"../data/raw/match_{MATCH_ID}_narrative.txt"
    META_FILE  = f"../data/raw/match_{MATCH_ID}_meta.csv"
    if os.path.exists(INPUT_FILE) and os.path.exists(META_FILE):
        tokenize_match_narrative(INPUT_FILE, match_id=MATCH_ID, meta_file=META_FILE,
                                 model_name="Qwen/Qwen2.5-1.5B",
                                 context_length=512, stride=256,
                                 label_window_minutes=5)
    else:
        print("Error: run data_pipeline.py first.")